export const GET_MASTER_SCHOOL_REQUEST = "GET_MASTER_SCHOOL_REQUEST"
export const GET_MASTER_SCHOOL_SCCUESS = "GET_MASTER_SCHOOL_SCCUESS"
export const GET_MASTER_SCHOOL_FAILED = "GET_MASTER_SCHOOL_FAILED"

export const GET_MASTER_CLASSES_REQUEST = "GET_MASTER_CLASSES_REQUEST"
export const GET_MASTER_CLASSES_SCCUESS = "GET_MASTER_CLASSES_SCCUESS"
export const GET_MASTER_CLASSES_FAILED = "GET_MASTER_CLASSES_FAILED"

export const CREATE_LEAD_CUSTOMER_REQUEST = "GET_CREATE_LEAD_CUSTOMER_REQUEST"
export const CREATE_LEAD_CUSTOMER_SCCUESS = "CREATE_LEAD_CUSTOMER_SCCUESS"
export const CREATE_LEAD_CUSTOMER_FAILED = "CREATE_LEAD_CUSTOMER_FAILED"